spring.jpa.hibernate.ddl-auto: none

spring.datasource.url: jdbc:mysql://localhost:3306/diplom
spring.datasource.username: root
spring.datasource.password: testskill

flyway.url: jdbc:mysql://localhost:3306
flyway.schemas: diplom
flyway.user: root
flyway.password: testskill
flyway.locations: filesystem:db/migration

config:
  captcha:
    timeout: 10
    image:
      width: 135
      height: 35