spring.jpa.hibernate.ddl-auto: none

spring.datasource.url: jdbc:mysql://localhost:3306/diplom?serverTimezone=UTC
spring.datasource.username: sqluser
spring.datasource.password: diplomsql

config:
  password:
    minlength: 6
  captcha:
    timeout: 10
    image:
      width: 110
      height: 35
  post:
    minlength:
      title: 3
      text: 50
  comment:
    minlength:
      text: 10
  restore:
    timeout: 10

upload:
  path: /project/diplom/uploads
  maxSize: 1048576
  expansion: jpg, png
  randomPart:
    value: 3
    length: 2

avatar:
  width: 36
  height: 36
  default: /default-1.png

email:
  host: smtp.gmail.com
  port: 465
  username: java10skillbox@gmail.com
  password: java10rezone